---
# tasks file for yauh.msmtp
- name: Install packages for msmtp and mailx
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - msmtp-mta
    - heirloom-mailx
    - ca-certificates

- name: Ensure to remove other MTAs
  apt: pkg={{ item }} state=removed
  with_items:
    - exim
    - postfix

- name: create msmtp config
  template: >
    src=msmtprc.j2 dest=/etc/msmtprc
    owner=root group=root mode=644

- name: create msmtp aliases
  template: >
    src=msmtp_aliases.j2 dest=/etc/msmtp_aliases
    owner=root group=root mode=644

- name: sending a testmail
  shell: echo "Configured msmtp for $(hostname -f) using ansible" | mail -s "[$(hostname -f)] MSMTP configured" {{ msmtp_default_recipient }}
  when: msmtp_send_testmail
